services:
  webview:
    image: node:lts
    command: sh -c 'yarn && yarn dev'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      # - HOST=0.0.0.0